//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/dagger/core/src/test/java/dagger/internal/MapProviderFactoryTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DaggerInternalMapProviderFactoryTest")
#ifdef RESTRICT_DaggerInternalMapProviderFactoryTest
#define INCLUDE_ALL_DaggerInternalMapProviderFactoryTest 0
#else
#define INCLUDE_ALL_DaggerInternalMapProviderFactoryTest 1
#endif
#undef RESTRICT_DaggerInternalMapProviderFactoryTest

#if !defined (DaggerInternalMapProviderFactoryTest_) && (INCLUDE_ALL_DaggerInternalMapProviderFactoryTest || defined(INCLUDE_DaggerInternalMapProviderFactoryTest))
#define DaggerInternalMapProviderFactoryTest_

@class OrgJunitRulesExpectedException;

@interface DaggerInternalMapProviderFactoryTest : NSObject {
 @public
  OrgJunitRulesExpectedException *thrown_;
}

#pragma mark Public

- (instancetype)init;

- (void)iterationOrder;

- (void)nullKey;

- (void)nullValue;

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerInternalMapProviderFactoryTest)

J2OBJC_FIELD_SETTER(DaggerInternalMapProviderFactoryTest, thrown_, OrgJunitRulesExpectedException *)

FOUNDATION_EXPORT void DaggerInternalMapProviderFactoryTest_init(DaggerInternalMapProviderFactoryTest *self);

FOUNDATION_EXPORT DaggerInternalMapProviderFactoryTest *new_DaggerInternalMapProviderFactoryTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DaggerInternalMapProviderFactoryTest *create_DaggerInternalMapProviderFactoryTest_init();

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalMapProviderFactoryTest)

#endif

#pragma pop_macro("INCLUDE_ALL_DaggerInternalMapProviderFactoryTest")
