//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/dagger/core/src/test/java/OneTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OneTest")
#ifdef RESTRICT_OneTest
#define INCLUDE_ALL_OneTest 0
#else
#define INCLUDE_ALL_OneTest 1
#endif
#undef RESTRICT_OneTest

#if !defined (OneTest_) && (INCLUDE_ALL_OneTest || defined(INCLUDE_OneTest))
#define OneTest_

@interface OneTest : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)runTests;

@end

J2OBJC_STATIC_INIT(OneTest)

FOUNDATION_EXPORT void OneTest_runTests();

FOUNDATION_EXPORT void OneTest_init(OneTest *self);

FOUNDATION_EXPORT OneTest *new_OneTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OneTest *create_OneTest_init();

J2OBJC_TYPE_LITERAL_HEADER(OneTest)

#endif

#if !defined (OneTest_BigMemRunListener_) && (INCLUDE_ALL_OneTest || defined(INCLUDE_OneTest_BigMemRunListener))
#define OneTest_BigMemRunListener_

#define RESTRICT_OrgJunitRunnerNotificationRunListener 1
#define INCLUDE_OrgJunitRunnerNotificationRunListener 1
#include "org/junit/runner/notification/RunListener.h"

@class OrgJunitRunnerDescription;

@interface OneTest_BigMemRunListener : OrgJunitRunnerNotificationRunListener

#pragma mark Public

- (void)testFinishedWithOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;

- (void)testStartedWithOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)description_;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OneTest_BigMemRunListener)

FOUNDATION_EXPORT void OneTest_BigMemRunListener_init(OneTest_BigMemRunListener *self);

FOUNDATION_EXPORT OneTest_BigMemRunListener *new_OneTest_BigMemRunListener_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OneTest_BigMemRunListener *create_OneTest_BigMemRunListener_init();

J2OBJC_TYPE_LITERAL_HEADER(OneTest_BigMemRunListener)

#endif

#pragma pop_macro("INCLUDE_ALL_OneTest")
