//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/dagger/core/src/test/java/dagger/internal/InstanceFactoryTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DaggerInternalInstanceFactoryTest")
#ifdef RESTRICT_DaggerInternalInstanceFactoryTest
#define INCLUDE_ALL_DaggerInternalInstanceFactoryTest 0
#else
#define INCLUDE_ALL_DaggerInternalInstanceFactoryTest 1
#endif
#undef RESTRICT_DaggerInternalInstanceFactoryTest

#if !defined (DaggerInternalInstanceFactoryTest_) && (INCLUDE_ALL_DaggerInternalInstanceFactoryTest || defined(INCLUDE_DaggerInternalInstanceFactoryTest))
#define DaggerInternalInstanceFactoryTest_

@class OrgJunitRulesExpectedException;

@interface DaggerInternalInstanceFactoryTest : NSObject {
 @public
  OrgJunitRulesExpectedException *thrown_;
}

#pragma mark Public

- (instancetype)init;

- (void)create_throwsNullPointerException;

- (void)instanceFactory;

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerInternalInstanceFactoryTest)

J2OBJC_FIELD_SETTER(DaggerInternalInstanceFactoryTest, thrown_, OrgJunitRulesExpectedException *)

FOUNDATION_EXPORT void DaggerInternalInstanceFactoryTest_init(DaggerInternalInstanceFactoryTest *self);

FOUNDATION_EXPORT DaggerInternalInstanceFactoryTest *new_DaggerInternalInstanceFactoryTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DaggerInternalInstanceFactoryTest *create_DaggerInternalInstanceFactoryTest_init();

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalInstanceFactoryTest)

#endif

#pragma pop_macro("INCLUDE_ALL_DaggerInternalInstanceFactoryTest")
