//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/dagger/core/src/test/java/dagger/internal/SingleCheckTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DaggerInternalSingleCheckTest")
#ifdef RESTRICT_DaggerInternalSingleCheckTest
#define INCLUDE_ALL_DaggerInternalSingleCheckTest 0
#else
#define INCLUDE_ALL_DaggerInternalSingleCheckTest 1
#endif
#undef RESTRICT_DaggerInternalSingleCheckTest

#if !defined (DaggerInternalSingleCheckTest_) && (INCLUDE_ALL_DaggerInternalSingleCheckTest || defined(INCLUDE_DaggerInternalSingleCheckTest))
#define DaggerInternalSingleCheckTest_

@interface DaggerInternalSingleCheckTest : NSObject

#pragma mark Public

- (instancetype)init;

- (void)create_nullPointerException;

- (void)get;

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerInternalSingleCheckTest)

FOUNDATION_EXPORT void DaggerInternalSingleCheckTest_init(DaggerInternalSingleCheckTest *self);

FOUNDATION_EXPORT DaggerInternalSingleCheckTest *new_DaggerInternalSingleCheckTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DaggerInternalSingleCheckTest *create_DaggerInternalSingleCheckTest_init();

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalSingleCheckTest)

#endif

#pragma pop_macro("INCLUDE_ALL_DaggerInternalSingleCheckTest")
