//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/core-doppl/androidbase/src/main/java/co/touchlab/doppl/ui/DPTextView.java
//

#include "CoTouchlabDopplUiDPTextView.h"
#include "J2ObjC_source.h"

@interface CoTouchlabDopplUiDPTextView : NSObject

@end

@implementation CoTouchlabDopplUiDPTextView

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(setTextWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "setText", "LNSString;" };
  static const J2ObjcClassInfo _CoTouchlabDopplUiDPTextView = { "DPTextView", "co.touchlab.doppl.ui", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_CoTouchlabDopplUiDPTextView;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(CoTouchlabDopplUiDPTextView)
