//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/core-doppl/androidbase/src/main/java/co/touchlab/doppl/ui/DPTextView.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoTouchlabDopplUiDPTextView")
#ifdef RESTRICT_CoTouchlabDopplUiDPTextView
#define INCLUDE_ALL_CoTouchlabDopplUiDPTextView 0
#else
#define INCLUDE_ALL_CoTouchlabDopplUiDPTextView 1
#endif
#undef RESTRICT_CoTouchlabDopplUiDPTextView

#if !defined (CoTouchlabDopplUiDPTextView_) && (INCLUDE_ALL_CoTouchlabDopplUiDPTextView || defined(INCLUDE_CoTouchlabDopplUiDPTextView))
#define CoTouchlabDopplUiDPTextView_

@protocol CoTouchlabDopplUiDPTextView < JavaObject >

- (void)setTextWithNSString:(NSString *)s;

@end

J2OBJC_EMPTY_STATIC_INIT(CoTouchlabDopplUiDPTextView)

J2OBJC_TYPE_LITERAL_HEADER(CoTouchlabDopplUiDPTextView)

#endif

#pragma pop_macro("INCLUDE_ALL_CoTouchlabDopplUiDPTextView")
