//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DaggerInternalDoubleCheckTest")
#ifdef RESTRICT_DaggerInternalDoubleCheckTest
#define INCLUDE_ALL_DaggerInternalDoubleCheckTest 0
#else
#define INCLUDE_ALL_DaggerInternalDoubleCheckTest 1
#endif
#undef RESTRICT_DaggerInternalDoubleCheckTest

#if !defined (DaggerInternalDoubleCheckTest_) && (INCLUDE_ALL_DaggerInternalDoubleCheckTest || defined(INCLUDE_DaggerInternalDoubleCheckTest))
#define DaggerInternalDoubleCheckTest_

@interface DaggerInternalDoubleCheckTest : NSObject

#pragma mark Public

- (instancetype)init;

- (void)doubleWrapping_lazy;

- (void)doubleWrapping_provider;

- (void)get;

- (void)lazy_nullPointerException;

- (void)provider_nullPointerException;

- (void)reentranceReturningDifferentInstances_throwsIllegalStateException;

- (void)reentranceReturningSameInstance;

- (void)reentranceWithoutCondition_throwsStackOverflow;

@end

J2OBJC_STATIC_INIT(DaggerInternalDoubleCheckTest)

FOUNDATION_EXPORT void DaggerInternalDoubleCheckTest_init(DaggerInternalDoubleCheckTest *self);

FOUNDATION_EXPORT DaggerInternalDoubleCheckTest *new_DaggerInternalDoubleCheckTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DaggerInternalDoubleCheckTest *create_DaggerInternalDoubleCheckTest_init();

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalDoubleCheckTest)

#endif

#pragma pop_macro("INCLUDE_ALL_DaggerInternalDoubleCheckTest")
