//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OneTest")
#ifdef RESTRICT_OneTest
#define INCLUDE_ALL_OneTest 0
#else
#define INCLUDE_ALL_OneTest 1
#endif
#undef RESTRICT_OneTest

#if !defined (OneTest_) && (INCLUDE_ALL_OneTest || defined(INCLUDE_OneTest))
#define OneTest_

@interface OneTest : NSObject

#pragma mark Public

- (instancetype)init;

+ (jint)runTests;

@end

J2OBJC_STATIC_INIT(OneTest)

FOUNDATION_EXPORT void OneTest_init(OneTest *self);

FOUNDATION_EXPORT OneTest *new_OneTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OneTest *create_OneTest_init();

FOUNDATION_EXPORT jint OneTest_runTests();

J2OBJC_TYPE_LITERAL_HEADER(OneTest)

#endif

#pragma pop_macro("INCLUDE_ALL_OneTest")
